[tools]
ruby = "3.4.6"

[tasks.build]
run = "gem build guard-puma.gemspec"
description = "Build the latest version"

[tasks.release]
run = """
#!/usr/bin/env bash
version="$(ruby -r ./lib/guard/puma/version.rb -e 'puts Guard::PumaVersion::VERSION')"
otp="$(op read "$OP_OTP")"
gem push guard-puma-$version.gem --otp $otp
"""
description = "Pushes the latest version to RubyGems"
depends = ["build"]
